[project]
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "moccasin>=0.3.6",
    "ruff>=0.8.6",
    "vyper==0.4.0",
]

[tool.moccasin.project]
src = "contracts"
dependencies = ["snekmate"]
